package id.hwaryun.core_data.model.viewparam

data class MovieDetailViewParam(
    val keywords: String? = null,
    val year: String? = null,
    val directors: String? = null,
    val title: String? = null,
    val type: String? = null,
    val tvEpisodeInfo: Any? = null,
    val imDbRating: String? = null,
    val trailer: Any? = null,
    val runtimeStr: String? = null,
    val plotLocal: String? = null,
    val companies: String? = null,
    val plot: String? = null,
    val genres: String? = null,
    val ratings: Any? = null,
    val imDbRatingVotes: String? = null,
    val tvSeriesInfo: Any? = null,
    val id: String? = null,
    val wikipedia: Any? = null,
    val fullCast: Any? = null,
    val image: String? = null,
    val fullTitle: String? = null,
    val images: Any? = null,
    val runtimeMins: String? = null,
    val languages: String? = null,
    val releaseDate: String? = null,
    val posters: Any? = null,
    val errorMessage: Any? = null,
    val metacriticRating: String? = null,
    val writers: String? = null,
    val stars: String? = null,
    val countries: String? = null,
    val plotLocalIsRtl: Boolean? = null,
    val originalTitle: String? = null,
    val awards: String? = null,
    val tagline: Any? = null,
    val contentRating: String? = null,
)